import ServicePageWrapper from "@components/ServicePageWrapper";
import type { NextPage } from "next";
import Head from "next/head";
import featuredImage from "public/assets/dokumentacja.jpg";
import Paragraph from "@components/Paragraph";
import ServiceHeading from "@components/ServiceHeading";

const UslugiAudytorskie: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ServicePageWrapper
        title="Dokumentacja cen transferowych"
        subtitle={
          <Paragraph>
            Do sporządzania dokumentacji cen transferowych, zgodnie z porządkiem prawnym obowiązującym od 2019 roku, są
            zobowiązane podmioty, których transakcje kontrolowane o jednorodnym charakterze z podmiotami powiązanymi
            przekraczają określone progi (w wartościach netto - pomniejszone o podatek od towarów i usług). Progi te są
            następujące: 10 mln zł - w przypadku transakcji towarowej i finansowej; 2 mln zł - w przypadku transakcji
            usługowej lub innej; 100 tys. zł - w przypadku transakcji prowadzonych z podmiotami zlokalizowanymi w rajach
            podatkowych.
          </Paragraph>
        }
        image={featuredImage}
        firm="warido"
        serviceId="s-dok"
      >
        <ServiceHeading>Progi dokumentacyjne są ustalane odrębnie dla</ServiceHeading>
        <ul>
          <li>
            każdej transakcji kontrolowanej o charakterze jednorodnym niezależnie od przyporządkowania transakcji
            kontrolowanej do transakcji towarowych, finansowych, usługowych albo innych transakcji.
          </li>
          <li>strony kosztowej i przychodowej.</li>
        </ul>
        <Paragraph>
          Z obowiązku sporządzania dokumentacji cen transferowych zwolnione są podmioty krajowe, gdy żaden z podmiotów
          uczestniczących w transakcji nie ponosi straty podatkowej w danym roku obrachunkowym oraz podmioty nie
          korzystają ze zwolnienia z podatku dochodowego (działalność w specjalnej strefie ekonomicznej oraz decyzja o
          wsparciu nowych inwestycji).
        </Paragraph>
        <Paragraph>
          Lokalna dokumentacja cen transferowych powinna zawierać m.in. opis podmiotu powiązanego, opis transakcji, w
          tym analizę funkcji, ryzyk i aktywów oraz analizę cen transferowych - analizę porównawczą lub analizę
          zgodności.
        </Paragraph>
        <Paragraph>
          Analiza porównawcza zawiera porównanie wartości następujących wskaźników podmiotów z branży: marżę operacyjną,
          marżę zysku brutto, rentowność aktywów oraz rentowność kapitału własnego.
        </Paragraph>
        <Paragraph>
          Posiadamy duże doświadczenie w zakresie sporządzania dokumentacji cen transferowych - zarówno według porządku
          prawnego obowiązującego przed 2019 rokiem, jak i aktualnie obowiązującego.
        </Paragraph>
        <Paragraph>
          Jeśli mają Państwo jakiekolwiek zapytania lub wątpliwości w zakresie obowiązku dokumentacyjnego dotyczącego
          transakcji z podmiotami powiązanymi służymy swoją wiedzą i pomocą.
        </Paragraph>
      </ServicePageWrapper>
    </>
  );
};

export default UslugiAudytorskie;
