import Button from "@components/Button";
import ContactForm from "@components/ContactForm";
import ContactInfo from "@components/ContactInfo";
import Container from "@components/Container";
import Footer from "@components/Footer";
import Header from "@components/Header";
import Hero from "@components/Hero";
import Paragraph from "@components/Paragraph";
import SectionTitle from "@components/SectionTitle";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  ArrowRight,
  At,
  BookBookmark,
  Checks,
  CurrencyCircleDollar,
  IconContext,
  MapPin,
  Phone,
  PhoneCall,
  Placeholder,
  UserCirclePlus,
} from "phosphor-react";
import styles from "styles/Home.module.scss";
import { Media, MediaContextProvider } from "utils/media";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Główna | Ranga &times; Warido</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container className={styles.wrapper}>
        <Header activeMenuItem="home" />
        <Hero />

        <section className={styles.about} id="about">
          <SectionTitle text="O Nas">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua
          </SectionTitle>
          <div className={styles.about__grid}>
            <div className={styles.item}>
              <h3 className={styles.item__title}>Kim jesteśmy?</h3>
              <Paragraph>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua
              </Paragraph>
            </div>
            <div className={styles.item}>
              <h3 className={styles.item__title}>Co robimy?</h3>
              <Paragraph>
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                pariatur
              </Paragraph>
            </div>
            <div className={styles.item}>
              <h3 className={styles.item__title}>Jak możemy pomóc?</h3>
              <Paragraph>
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
                laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem
              </Paragraph>
            </div>
          </div>
          <Button size="small" linkTo="/about" icon={ArrowRight}>
            Dowiedz się więcęj
          </Button>
        </section>

        <section className={styles.services} id="services">
          <SectionTitle text="Usługi">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, tempor incididunt ut labore et dolore magna aliqua
          </SectionTitle>
          <IconContext.Provider value={{ size: 36, color: "var(--clr-accent)" }}>
            <MediaContextProvider>
              <div className={styles.services__grid}>
                <Link href="/about">
                  <a draggable="false" className={styles.item}>
                    <BookBookmark />
                    <div>
                      <h4 className={styles.item__title}>Usługi Audytorskie</h4>
                      <Media lessThan="lg">
                        <Paragraph>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</Paragraph>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Więcej
                        </Button>
                      </Media>
                      <Media greaterThan="md">
                        <Paragraph>Świadczymy usługi w zakresie:</Paragraph>
                        <ul>
                          <li>Badanie sprawozdań fiansowych</li>
                          <li>Badanie planów przekrztałcenia</li>
                          <li>Badanie planów połączenia</li>
                          <li>Audyt projektów unijnych</li>
                          <li>Analizy finansowe</li>
                        </ul>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Dowiedz się więcej
                        </Button>
                      </Media>
                    </div>
                  </a>
                </Link>
                <Link href="/about">
                  <a draggable="false" className={styles.item}>
                    <Checks />
                    <div>
                      <h4 className={styles.item__title}>Usługi Księgowe</h4>
                      <Media lessThan="lg">
                        <Paragraph>Lorem ipsum dolor sit amet consectetur.</Paragraph>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Więcej
                        </Button>
                      </Media>
                      <Media greaterThan="md">
                        <Paragraph>
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                          labore et dolore magna aliqua
                        </Paragraph>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Dowiedz się więcej
                        </Button>
                      </Media>
                    </div>
                  </a>
                </Link>
                <Link href="/about">
                  <a draggable="false" className={styles.item}>
                    <UserCirclePlus />
                    <div>
                      <h4 className={styles.item__title}>Zakładanie spółek</h4>
                      <Media lessThan="lg">
                        <Paragraph>Lorem ipsum dolor sit amet.</Paragraph>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Więcej
                        </Button>
                      </Media>
                      <Media greaterThan="md">
                        <Paragraph>
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                          labore et dolore magna aliqua
                        </Paragraph>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Dowiedz się więcej
                        </Button>
                      </Media>
                    </div>
                  </a>
                </Link>
                <Link href="/about">
                  <a draggable="false" className={styles.item}>
                    <CurrencyCircleDollar />
                    <div>
                      <h4 className={styles.item__title}>Dokumentacja cen transferowych</h4>
                      <Media lessThan="lg">
                        <Paragraph>Lorem ipsum dolor sit amet.</Paragraph>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Więcej
                        </Button>
                      </Media>
                      <Media greaterThan="md">
                        <Paragraph>
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                          labore et dolore magna aliqua
                        </Paragraph>
                        <Button className={styles.item__button} size="small" icon={ArrowRight}>
                          Dowiedz się więcej
                        </Button>
                      </Media>
                    </div>
                  </a>
                </Link>
              </div>
            </MediaContextProvider>
          </IconContext.Provider>
        </section>
      </Container>
      <section className={styles.stats}>
        <Container>
          <SectionTitle text="Możesz nam zaufać" forceColor="white" />
          <div className={styles.stats__grid}>
            <div className={styles.item}>
              <div className={styles.number}>
                15<span>+</span>
              </div>
              <div className={styles.text}>Lat Doświadczenia</div>
            </div>

            <div className={styles.item}>
              <div className={styles.number}>
                100<span>+</span>
              </div>
              <div className={styles.text}>Zadowolonych Klientów</div>
            </div>

            <div className={styles.item}>
              <div className={styles.number}>8</div>
              <div className={styles.text}>Dyplomów</div>
            </div>

            <div className={styles.item}>
              <div className={styles.number}>10</div>
              <div className={styles.text}>Wykształconych Pracowników</div>
            </div>

            <div className={styles.item}>
              <div className={styles.number}>
                50<span>+</span>
              </div>
              <div className={styles.text}>Certyfikatów</div>
            </div>
          </div>
        </Container>
      </section>
      <Container>
        <MediaContextProvider>
          <section className={styles.contact} id="contact">
            <Media greaterThanOrEqual="md">
              <div className={styles.watermark}>
                <PhoneCall size={330} color="var(--clr-accent)" />
              </div>
            </Media>
            <SectionTitle className={styles.contact__title} text="Skontaktuj się z nami">
              Jesteś zainteresowany naszymi usługami? Możesz skontaktować się z nami za pomocą formularza lub danych
              poniżej
            </SectionTitle>
            <div className={styles.info}>
              <h3 className={styles.info__title}>Nasze dane kontaktowe</h3>
              <div className={styles.info__grid}>
                <Media lessThan="md">
                  <ContactInfo icon={At} data={["info@ranga.net.pl"]} />
                </Media>
                <Media lessThan="md">
                  <ContactInfo icon={At} data={["info@audytasg.pl"]} />
                </Media>
                <Media greaterThanOrEqual="md">
                  <ContactInfo icon={At} data={["info@ranga.net.pl", "info@audytasg.pl"]} />
                </Media>
                <Media lessThan="md">
                  <ContactInfo icon={Phone} data={["+(48) 515 096 788"]} />
                </Media>
                <Media lessThan="md">
                  <ContactInfo icon={Phone} data={["+(48) 33 818 43 17"]} />
                </Media>
                <Media greaterThanOrEqual="md">
                  <ContactInfo icon={Phone} data={["+(48) 515 096 788", "+(48) 33 818 43 17"]} />
                </Media>
                <ContactInfo icon={MapPin} data={["ul. Tadeusza 8, Bielsko-Biała 43-382"]} />
              </div>
            </div>

            <ContactForm />
          </section>
        </MediaContextProvider>
      </Container>
      <Footer />
    </>
  );
};

export default Home;
