import Container from "@components/Container";
import Header from "@components/Header";
import ServicePageWrapper from "@components/ServicePageWrapper";
import type { NextPage } from "next";
import Head from "next/head";
import featuredImage from "public/assets/ksiegowe.jpg";
import Paragraph from "@components/Paragraph";
import ServiceHeading from "@components/ServiceHeading";

const UslugiKsiegowe: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ServicePageWrapper
        title="Usługi Księgowe"
        subtitle={
          <Paragraph>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam laboriosam enim incidunt repellendus
            tenetur, nobis nulla aliquam
          </Paragraph>
        }
        image={featuredImage}
        firm="ranga"
        serviceId="s-ks"
      >
        <ServiceHeading>Świadczymy usługi w zakresie</ServiceHeading>
        <ul>
          <li>
            Prowadzenia ksiąg rachunkowych i podatkowej książki przychodów i rozchodów na podstawie dokumentacji
            dostarczanej przez klienta zarówno w naszej kancelarii, na naszym programie księgowym, jak i u klienta, na
            jego programie księgowym.
          </li>
          <li>Nadzoru nad prawidłowym obiegiem dokumentów księgowych.</li>
          <li>
            Opracowywania planu kont zgodnie ze standardami sprawozdawczymi, wymogami kontrolingu oraz prawem
            podatkowym.
          </li>
          <li>Zapewnienia prawidłowości rozliczeń podatkowych.</li>
          <li>Sporządzania deklaracji podatkowych oraz innych dokumentów i raportów wymaganych przepisami prawa.</li>
          <li>Sporządzania sprawozdań finansowych według standardów przyjętych w polityce rachunkowości.</li>
          <li>Przygotowywania sprawozdań i raportów na potrzeby zarządu, banków oraz instytucji zewnętrznych.</li>
          <li>Realizowania procedury potwierdzania sald z kontrahentami, rozliczanie inwentaryzacji aktywów firmy.</li>
          <li>Współpracy w opracowywaniu wniosków kredytowych.</li>
          <li>Udzielania porad oraz wyjaśnień księgowo-podatkowych.</li>
          <li>
            Obsługi kadrowo-płacowej - rejestracji pracodawcy i pracowników dla celów ubezpieczenia społecznego,
            przygotowywaniu list płac dla pracowników zatrudnionych na podstawie umowy o pracę i innych form
            zatrudnienia oraz odpowiadających im rozliczeń podatku dochodowego od osób fizycznych i składek na
            ubezpieczenie społeczne, sporządzaniu deklaracji miesięcznych i rocznych.
          </li>
        </ul>
      </ServicePageWrapper>
    </>
  );
};

export default UslugiKsiegowe;
