import ServicePageWrapper from "@components/ServicePageWrapper";
import type { NextPage } from "next";
import Head from "next/head";
import featuredImage from "public/assets/tworzenie.jpg";
import Paragraph from "@components/Paragraph";
import ServiceHeading from "@components/ServiceHeading";

const ZakladanieSpolek: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ServicePageWrapper
        title="Zakładanie spółek"
        subtitle={
          <Paragraph>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua
          </Paragraph>
        }
        image={featuredImage}
        firm="warido"
        serviceId="s-zk"
      >
        <ServiceHeading>Lorem ipsum dolor sit.</ServiceHeading>
        <ul>
          <li>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Dictum non consectetur a erat. Mauris a diam maecenas sed. A lacus vestibulum sed arcu
            non odio euismod lacinia. Lacus sed viverra tellus in hac habitasse. Arcu non sodales neque sodales ut etiam
            sit amet. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Fermentum leo vel orci porta non
            pulvinar neque. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Ipsum suspendisse ultrices
            gravida dictum fusce ut placerat. Pellentesque habitant morbi tristique senectus et. Orci eu lobortis
            elementum nibh tellus molestie. Suspendisse in est ante in nibh mauris cursus. Gravida dictum fusce ut
            placerat.
          </li>
          <li>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ducimus veniam dolor, unde aliquam quia
            voluptatibus excepturi dolore! Itaque, doloribus eveniet! Vitae, hic soluta. Ipsam, vel mollitia harum fugit
            accusamus molestiae.
          </li>
        </ul>
      </ServicePageWrapper>
    </>
  );
};

export default ZakladanieSpolek;
